siemens/element

.github/workflows/build.yaml

With this change we upload the documetation as an artifact together with the examples.
---

build: upload documentation with examples

---

.github/workflows/release.yaml

This is needed to bypass branch protection.
Otherwise, the release will fail.
I hope I now reproduced the situation correctly in my repo.
With that change I got it working.
---

build: use gh token for checkout

---

projects/live-preview/components/si-live-preview-renderer/si-live-preview-renderer.component.ts

We also fixed this internally.
---

refactor(live-preview): fix typo

---

.github/workflows/build-and-test.yaml

This is needed to have the translation template available. 
---

build(github): make template-i18n available as artifact

---

CONTRIBUTING.md

docs(contributing): fix minor typo by adding a comma

---

docs/components/index.md
docs/components/status-notifications/copyright-notice.md
mkdocs.yml
projects/element-ng/copyright-notice/index.ts
projects/element-ng/copyright-notice/ng-package.json
projects/element-ng/copyright-notice/si-copyright-notice.component.html
projects/element-ng/copyright-notice/si-copyright-notice.component.spec.ts
projects/element-ng/copyright-notice/si-copyright-notice.component.ts
projects/element-ng/copyright-notice/si-copyright-notice.module.ts
projects/element-ng/copyright-notice/si-copyright-notice.ts
src/app/examples/si-copyright-notice/si-copyright-notice.html
src/app/examples/si-copyright-notice/si-copyright-notice.ts

feat(copyright-notice): introduce copyright notice

---

projects/element-ng/auto-collapsable-list/index.ts
projects/element-ng/auto-collapsable-list/ng-package.json
projects/element-ng/auto-collapsable-list/si-auto-collapsable-list-additional-content.directive.ts
projects/element-ng/auto-collapsable-list/si-auto-collapsable-list-item.directive.ts
projects/element-ng/auto-collapsable-list/si-auto-collapsable-list-measurable.class.ts
projects/element-ng/auto-collapsable-list/si-auto-collapsable-list-overflow-item.directive.ts
projects/element-ng/auto-collapsable-list/si-auto-collapsable-list.directive.spec.ts
projects/element-ng/auto-collapsable-list/si-auto-collapsable-list.directive.ts
projects/element-ng/auto-collapsable-list/si-auto-collapsable-list.module.ts

feat(auto-collapsable-list): add auto-collapsable list components and directives

---

CODEOWNERS

We want to require code owner review and not allow writers to merge their own pull requests anymore.
---

chore(CODEOWNERS): add fh1ch

---

projects/element-ng/autocomplete/index.ts
projects/element-ng/autocomplete/ng-package.json
projects/element-ng/autocomplete/si-autocomplete-listbox.directive.ts
projects/element-ng/autocomplete/si-autocomplete-option.directive.ts
projects/element-ng/autocomplete/si-autocomplete.directive.spec.ts
projects/element-ng/autocomplete/si-autocomplete.directive.ts
projects/element-ng/autocomplete/si-autocomplete.model.ts
projects/element-ng/autocomplete/si-autocomplete.module.ts

feat(autocomplete): add autocomplete directives and module

---

tsdoc.json

fix(tsdoc): add default ref

---

playwright/e2e/element-examples/wizard-vertical.spec.ts
playwright/snapshots/wizard-vertical.spec.ts-snapshots/si-wizard--si-wizard-playground--focus-element-examples-chromium-dark-linux.png
playwright/snapshots/wizard-vertical.spec.ts-snapshots/si-wizard--si-wizard-playground--focus-element-examples-chromium-light-linux.png
playwright/snapshots/wizard-vertical.spec.ts-snapshots/si-wizard--si-wizard-playground--focus.yaml
playwright/snapshots/wizard-vertical.spec.ts-snapshots/si-wizard--si-wizard-playground--horizontal-element-examples-chromium-dark-linux.png
playwright/snapshots/wizard-vertical.spec.ts-snapshots/si-wizard--si-wizard-playground--horizontal-element-examples-chromium-light-linux.png
playwright/snapshots/wizard-vertical.spec.ts-snapshots/si-wizard--si-wizard-playground--horizontal.yaml
playwright/snapshots/wizard-vertical.spec.ts-snapshots/si-wizard--si-wizard-playground--step-numbers-element-examples-chromium-dark-linux.png
playwright/snapshots/wizard-vertical.spec.ts-snapshots/si-wizard--si-wizard-playground--step-numbers-element-examples-chromium-light-linux.png
playwright/snapshots/wizard-vertical.spec.ts-snapshots/si-wizard--si-wizard-playground--step-numbers.yaml
playwright/snapshots/wizard-vertical.spec.ts-snapshots/si-wizard--si-wizard-playground--vertical-divider-element-examples-chromium-dark-linux.png
playwright/snapshots/wizard-vertical.spec.ts-snapshots/si-wizard--si-wizard-playground--vertical-divider-element-examples-chromium-light-linux.png
playwright/snapshots/wizard-vertical.spec.ts-snapshots/si-wizard--si-wizard-playground--vertical-divider.yaml
playwright/snapshots/wizard-vertical.spec.ts-snapshots/si-wizard--si-wizard-playground-element-examples-chromium-dark-linux.png
playwright/snapshots/wizard-vertical.spec.ts-snapshots/si-wizard--si-wizard-playground-element-examples-chromium-light-linux.png
playwright/snapshots/wizard-vertical.spec.ts-snapshots/si-wizard--si-wizard-playground.yaml
src/app/examples/si-wizard/si-wizard-playground.html
src/app/examples/si-wizard/si-wizard-playground.ts

Provide e2e tests to prevent unattended visual changes
---

test(wizard): introduce e2e tests

---

.github/workflows/build-and-test.yaml
.lfsconfig

Removes the workaround using another LFS endpoint.
---

build(e2e): use repository LFS endpoint

---

docs/fundamentals/colors/ui-colors.md
projects/element-theme/src/styles/variables/_semantic-tokens.scss
projects/element-theme/src/theme/_theme-element.scss

feat(theme): introduce text-critical token

---

src/app/examples/si-pills-input/si-pills-input.html
src/app/examples/si-pills-input/si-pills-input.ts

refactor(pills-input): update example email addresses

---

docs/components/forms-inputs/file-uploader.md

docs(file-uploader): update correct reference

---

projects/element-ng/localization/index.ts
projects/element-ng/localization/ng-package.json
projects/element-ng/localization/si-directionality.ts
projects/element-ng/localization/si-locale-id.spec.ts
projects/element-ng/localization/si-locale-id.ts
projects/element-ng/localization/si-locale-store.spec.ts
projects/element-ng/localization/si-locale-store.ts
projects/element-ng/localization/si-locale.service.spec.ts
projects/element-ng/localization/si-locale.service.ts
src/app/examples/si-localization/date-impure.pipe.ts
src/app/examples/si-localization/demo-locale.service.ts
src/app/examples/si-localization/si-localization.html
src/app/examples/si-localization/si-localization.ts

feat(localization): add localization service and related components

---

mkdocs.yml

docs: add user analytics scripts to documentation

---

projects/element-ng/inline-notification/si-inline-notification.component.html
projects/element-ng/inline-notification/si-inline-notification.component.ts

refactor(inline-notification): use status-icon for inline notification

---

projects/element-ng/shadow-root/index.ts
projects/element-ng/shadow-root/ng-package.json
projects/element-ng/shadow-root/si-shadow-root.directive.spec.ts
projects/element-ng/shadow-root/si-shadow-root.directive.ts
src/app/examples/si-shadow-root/not-element-styles.scss
src/app/examples/si-shadow-root/si-shadow-root.html
src/app/examples/si-shadow-root/si-shadow-root.ts

feat(shadow-root): add shadow-root

---

projects/element-ng/modal/si-modal.service.ts

feat(modal): ensure compatibility to Angular CDK 20

---

angular.json

build(angular): add google-libphonenumber to CommonJS deps

---

src/app/examples/si-form/si-form-legacy.html
src/app/examples/si-form/si-form-legacy.ts
src/app/examples/si-form/si-form.html
src/app/examples/si-form/si-form.ts

feat(form): add form examples

---

projects/element-ng/filtered-search/si-filtered-search.component.spec.ts

refactor(test): update TODO comment to remove issue reference

---

projects/element-ng/breadcrumb-router/index.ts
projects/element-ng/breadcrumb-router/ng-package.json
projects/element-ng/breadcrumb-router/si-breadcrumb-default-resolver.service.spec.ts
projects/element-ng/breadcrumb-router/si-breadcrumb-default-resolver.service.ts
projects/element-ng/breadcrumb-router/si-breadcrumb-router.component.html
projects/element-ng/breadcrumb-router/si-breadcrumb-router.component.spec.ts
projects/element-ng/breadcrumb-router/si-breadcrumb-router.component.ts
projects/element-ng/breadcrumb-router/si-breadcrumb-router.model.ts
projects/element-ng/breadcrumb-router/si-breadcrumb-router.module.ts
src/app/examples/si-breadcrumb-router/si-breadcrumb-router.html
src/app/examples/si-breadcrumb-router/si-breadcrumb-router.ts

feat(breadcrumb-router): add breadcrumb router component and resolver service

---

package.json

`ng-packagr` copies it automatically
---

chore(package): remove unnecessary copy for readme

---

package-lock.json
package.json
projects/element-theme/src/styles/components/_datatable.scss
projects/element-translate-ng/README.md

Finally formatting SCSS with multi-line :is() correctly
---

chore(deps): update prettier to 3.6

---

projects/live-preview/components/si-dummy.component.ts
projects/live-preview/components/si-example-overview/si-example-overview.component.ts
projects/live-preview/components/si-example-viewer/si-example-viewer.component.ts
projects/live-preview/components/si-live-preview-iframe/si-live-preview-iframe.component.ts
projects/live-preview/components/si-live-preview-qr/si-live-preview-qr.component.ts
projects/live-preview/components/si-live-preview-renderer/si-live-preview-renderer.component.ts
projects/live-preview/components/si-live-preview-renderer/webcomponent/si-live-preview-web.component.ts
projects/live-preview/components/si-live-preview-wrapper/si-live-preview-wrapper.component.ts
projects/live-preview/components/si-live-preview/si-live-preview.component.ts
projects/live-preview/public-api.module.ts

Should have been done a long time ago.
---

refactor(live-preview): migrate to standalone components

---

eslint.config.js
projects/element-ng/form/si-form-validation-error.service.ts
projects/element-translate-ng/ngx-translate/si-translate-ngxt.service.ts
projects/live-preview/components/si-dummy.component.ts

refactor(lint): use inject function

---

projects/element-theme/src/theme/_base-colors.scss
projects/element-theme/src/theme/_theme-element.scss

Aligned with internal tokens (modified colors)
---

feat: add experimental new tokens for ai patterns in themes

---

projects/dashboards-demo/src/app/components/widget-catalog/custom-widget-catalog.component.ts
projects/dashboards-ng/src/components/widget-catalog/si-widget-catalog.component.ts

refactor(dashboards-ng): drop some module imports

---

playwright/e2e/element-examples/static.spec.ts
playwright/snapshots/static.spec.ts-snapshots/si-electron-titlebar--si-fixed-height-layout-side-panel-element-examples-chromium-dark-linux.png
playwright/snapshots/static.spec.ts-snapshots/si-electron-titlebar--si-fixed-height-layout-side-panel-element-examples-chromium-light-linux.png
playwright/snapshots/static.spec.ts-snapshots/si-electron-titlebar--si-fixed-height-layout-side-panel.yaml
src/app/examples/si-electron-titlebar/si-fixed-height-layout-side-panel.html
src/app/examples/si-electron-titlebar/si-fixed-height-layout-side-panel.ts

docs(electron-titlebar): add missing example

---

playwright/e2e/element-examples/wizard-vertical.spec.ts
playwright/snapshots/wizard-vertical.spec.ts-snapshots/si-wizard--si-wizard-playground--disabled-steps-element-examples-chromium-dark-linux.png
playwright/snapshots/wizard-vertical.spec.ts-snapshots/si-wizard--si-wizard-playground--disabled-steps-element-examples-chromium-light-linux.png
playwright/snapshots/wizard-vertical.spec.ts-snapshots/si-wizard--si-wizard-playground--disabled-steps-numbered-element-examples-chromium-dark-linux.png
playwright/snapshots/wizard-vertical.spec.ts-snapshots/si-wizard--si-wizard-playground--disabled-steps-numbered-element-examples-chromium-light-linux.png
playwright/snapshots/wizard-vertical.spec.ts-snapshots/si-wizard--si-wizard-playground--disabled-steps-numbered.yaml
playwright/snapshots/wizard-vertical.spec.ts-snapshots/si-wizard--si-wizard-playground--disabled-steps.yaml
projects/element-ng/wizard/si-wizard.component.html
projects/element-ng/wizard/si-wizard.component.scss

fix(wizard): update disabled styles to match with figma

---

.docs-composerrc.mts
package-lock.json
package.json

chore(deps): bump docs composer and adjust config

---

.releaserc.js

build(release): use `release` instead of `maintenance` branches

---

projects/element-docs-builder/mkdocs_element_docs_builder/docs-builder.css
projects/element-docs-builder/mkdocs_element_docs_builder/docs-builder.js

The same as internal, this CSS/JS is needed and was incorrectly removed.
---

chore(docs-builder): fix collapsible sections

---

projects/element-ng/tabs-next/si-tab-next-base.directive.ts
projects/element-ng/tabs-next/si-tabset-next.component.html
projects/element-ng/tabs-next/si-tabset-next.component.spec.ts
projects/element-ng/tabs-next/si-tabset-next.component.ts
projects/element-ng/tabs-next/testing/si-tabset-next.harness.ts

refactor(tabs-next): process most events in focus key manager

---

.github/workflows/build-and-test.yaml

build(github): pull request preview deployments

---

projects/charts-ng/src/components/si-chart-gauge/si-chart-gauge.component.ts

feat(charts/gauge): support custom value formatter

---

projects/element-ng/autocomplete/si-autocomplete-listbox.directive.ts

refactor(autocomplete): use signal queries

---

projects/element-ng/auto-collapsable-list/si-auto-collapsable-list-item.directive.ts
projects/element-ng/auto-collapsable-list/si-auto-collapsable-list-measurable.class.ts
projects/element-ng/auto-collapsable-list/si-auto-collapsable-list.directive.ts
projects/element-ng/filter-bar/si-filter-bar.component.ts

refactor(auto-collapsable-list): use query signals

---

projects/element-ng/summary-widget/si-summary-widget.component.html
projects/element-ng/summary-widget/si-summary-widget.component.spec.ts
projects/element-ng/summary-widget/si-summary-widget.component.ts

refactor(summary-widget):  use si icon next

---

projects/element-ng/status-toggle/si-status-toggle.component.html
projects/element-ng/status-toggle/si-status-toggle.component.ts

refactor(status-toggle): use si icon next

---

projects/element-ng/wizard/si-wizard.component.html
projects/element-ng/wizard/si-wizard.component.ts

refactor(wizard): use signal queries internally

---

.github/workflows/build-and-test.yaml

Up to 30s faster than before.
---

build(github): remove unused dependencies from e2e merge report

---

playwright/snapshots/static.spec.ts-snapshots/si-landing-page--si-landing-page-custom-element-examples-chromium-dark-linux.png
playwright/snapshots/static.spec.ts-snapshots/si-landing-page--si-landing-page-custom-element-examples-chromium-light-linux.png
src/app/examples/si-landing-page/si-landing-page-custom.html

docs(landing-page): use different background image in custom example

---

src/app/examples/si-main-detail-container/si-main-detail-container-block.html
src/app/examples/si-main-detail-container/si-main-detail-container-block.ts
src/app/examples/si-main-detail-container/si-main-detail-container-filtered-search.ts
src/app/examples/si-main-detail-container/si-main-detail-container.html
src/app/examples/si-main-detail-container/si-main-detail-container.ts

chore(examples): fix broken main detail examples

---

playwright/snapshots/si-form.spec.ts-snapshots/si-form--si-form--large-element-examples-chromium-dark-linux.png
playwright/snapshots/si-form.spec.ts-snapshots/si-form--si-form--large-element-examples-chromium-light-linux.png
playwright/snapshots/si-form.spec.ts-snapshots/si-form--si-form--large-validated-element-examples-chromium-dark-linux.png
playwright/snapshots/si-form.spec.ts-snapshots/si-form--si-form--large-validated-element-examples-chromium-light-linux.png
playwright/snapshots/si-form.spec.ts-snapshots/si-form--si-form-element-examples-chromium-dark-linux.png
playwright/snapshots/si-form.spec.ts-snapshots/si-form--si-form-element-examples-chromium-light-linux.png
src/app/examples/si-form/si-form.html
src/app/examples/si-form/si-form.ts

docs(form): use date input with calendar-button

---

playwright/snapshots/si-form.spec.ts-snapshots/si-form--si-form--large-validated.yaml
playwright/snapshots/si-form.spec.ts-snapshots/si-form--si-form--large.yaml
playwright/snapshots/si-form.spec.ts-snapshots/si-form--si-form.yaml
src/app/examples/si-form/si-form.html
src/app/examples/si-form/si-form.ts

docs(form): migrate form actions to si-form-fieldset

---

projects/element-ng/typeahead/si-typeahead.component.html
projects/element-ng/typeahead/si-typeahead.component.ts

refactor(typeahead): use signals and remove unnecessary code

---

projects/element-ng/popover-next/si-popover-next.directive.ts
projects/element-ng/popover-next/si-popover.component.html
src/app/examples/si-popover-next/si-popover-next.html

refactor(popover): standardize input aliases and update template references

---

projects/element-ng/color-picker/si-color-picker.component.html
projects/element-ng/color-picker/si-color-picker.component.ts

refactor(color-picker): don't use dom query selectors

---

projects/element-ng/password-strength/si-password-strength.component.ts

refactor(password-strength): replace dom query selector with signal query

---

projects/element-ng/tabs-next/si-tab-next-base.directive.ts
projects/element-ng/tabs-next/si-tab-next-link.component.ts
projects/element-ng/tabs-next/si-tab-next.component.ts
projects/element-ng/tabs-next/si-tabset-next.component.ts

Make this component production ready
by making the API as restrive as possible.
---

refactor(tabs-next): harden the API

---

.github/workflows/build-and-test.yaml

Using the hash is causing many updates. Using a version instead should reduce the amount of updates.
---

build(github): use fixed aws-actions version

---

.github/workflows/build-and-test.yaml

build(github): use correct version pattern for aws-actions

---

projects/dashboards-ng/src/components/dashboard-toolbar/si-dashboard-toolbar.component.html

Adds consistency with other buttons in the dashboard
---

feat(dashboard-toolbar): add title attribute to edit button

---

projects/native-charts-ng/micro-donut/index.ts
projects/native-charts-ng/micro-donut/ng-package.json
projects/native-charts-ng/micro-donut/si-micro-donut.component.html
projects/native-charts-ng/micro-donut/si-micro-donut.component.scss
projects/native-charts-ng/micro-donut/si-micro-donut.component.ts
src/app/examples/si-ncharts/si-micro-charts.html
src/app/examples/si-ncharts/si-micro-charts.ts

feat(micro-charts): add micro donut chart

---

projects/native-charts-ng/micro-progress/index.ts
projects/native-charts-ng/micro-progress/ng-package.json
projects/native-charts-ng/micro-progress/si-micro-progress.component.html
projects/native-charts-ng/micro-progress/si-micro-progress.component.scss
projects/native-charts-ng/micro-progress/si-micro-progress.component.ts
src/app/examples/si-ncharts/si-micro-progress.html
src/app/examples/si-ncharts/si-micro-progress.ts

feat(micro-charts): add micro progress chart

---

projects/element-ng/accordion/si-collapsible-panel.component.scss

fix(accordion): don't switch to cursor pointer in case of disabled panel

---

projects/element-ng/date-range-filter/si-date-range-filter.component.ts

Fixes a bug when you clear the `to` date in input mode, the control switches to advanced mode
---

fix(date-range-filter): stop automatic advanced mode toggle in input mode

---

projects/element-ng/help-button/si-help-button.component.scss

fix(help-button): don't change color on hover when disabled

---

projects/dashboards-demo/src/app/widgets/charts/value-widget-editor.component.ts
projects/element-ng/form/si-form.spec.ts
src/app/examples/si-form/si-form.html

docs(form): remove unnecessary properties from form example

---

projects/dashboards-demo/webcomponents/concat.cjs

chore(dashboards): enable repeated dashboards webcomponent build

---

docs/components/charts/micro-charts.md

docs(micro-charts): add code section

---

projects/element-ng/action-modal/si-action-dialog.types.ts

just shows up everytime we run lint. 
---

chore(lint): remove unnecessary rule disable

---

projects/element-ng/formly/structural/si-formly-tabset/si-formly-object-tabset.component.html
projects/element-ng/formly/structural/si-formly-tabset/si-formly-object-tabset.component.spec.ts
projects/element-ng/formly/structural/si-formly-tabset/si-formly-object-tabset.component.ts

refactor(formly): use `si-tab-next`

---

playwright/e2e/element-examples/si-select.spec.ts

test(playwright): use `getByRole` instead to locator-nth for `si-select`

---

playwright/snapshots/si-launchpad.spec.ts-snapshots/si-application-header--si-launchpad--mobile.yaml
playwright/snapshots/si-launchpad.spec.ts-snapshots/si-application-header--si-launchpad--new-favorite.yaml
playwright/snapshots/si-launchpad.spec.ts-snapshots/si-application-header--si-launchpad.yaml
projects/element-ng/application-header/launchpad/si-launchpad-factory.component.html
projects/element-ng/application-header/launchpad/si-launchpad-factory.component.ts
projects/element-ng/application-header/launchpad/si-launchpad.model.ts
src/app/examples/si-application-header/si-launchpad.ts

feat(launchpad): support `routerLink` for launchpad apps

---

projects/charts-ng/README.md
projects/dashboards-ng/translate/si-translatable-keys.interface.ts
projects/element-ng/translate/si-translatable-keys.interface.ts
projects/element-translate-cli/bin/update-translatable-keys.js
projects/element-translate-ng/README.md
projects/native-charts-ng/README.md

chore: replace yarn commands with npm

---

playwright/snapshots/charts/static.spec.ts-snapshots/si-charts--interactive--interactive-element-examples-chromium-light-linux.png
playwright/snapshots/datatable-row-group.spec.ts-snapshots/datatable--datatable-grouped-rows--collapsed-element-examples-chromium-light-linux.png
playwright/snapshots/datatable-row-group.spec.ts-snapshots/datatable--datatable-grouped-rows--default-element-examples-chromium-light-linux.png
playwright/snapshots/datatable-row-group.spec.ts-snapshots/datatable--datatable-grouped-rows--group-selection-element-examples-chromium-light-linux.png
playwright/snapshots/datatable-row-group.spec.ts-snapshots/datatable--datatable-grouped-rows--row-selection-element-examples-chromium-light-linux.png
projects/element-ng/datatable/si-datatable-interaction.directive.spec.ts
src/app/examples/datatable/datatable-grouped-rows.html
src/app/examples/drag-drop/drag-drop-cards.html
src/app/examples/si-charts/interactive/interactive.html

chore(demo): drop elevation shadows

---

projects/element-ng/toast-notification/si-toast-notification/si-toast-notification.component.html
projects/element-ng/toast-notification/si-toast-notification/si-toast-notification.component.ts

refactor(toast-notification): use signals for internals

---

projects/element-ng/breadcrumb-router/si-breadcrumb-default-resolver.service.ts

refactor(breadcrumb-router): use better variable name

---

projects/element-ng/card/si-card.component.ts

chore(card): remove redundant comment

---

playwright/snapshots/dashboard.spec.ts-snapshots/dashboard--edit.yaml
playwright/snapshots/datatable-tree.spec.ts-snapshots/datatable--datatable--invalid-age.yaml
playwright/snapshots/datatable-tree.spec.ts-snapshots/datatable--datatable.yaml
playwright/snapshots/static.spec.ts-snapshots/list-group--list-group.yaml
playwright/snapshots/static.spec.ts-snapshots/si-circle-status--si-circle-status.yaml
projects/element-ng/circle-status/si-circle-status.component.ts

fix(circle-status): correct spacing in aria label generation

---

projects/element-translate-ng/ng-package.json

build(translate-ng): add missing `localize-types/index.d.ts` file

---

.github/workflows/build-and-test.yaml

ci: fix spelling in PR comment

---

angular.json
projects/dashboards-demo/mfe/webpack.prod.config.cjs

refactor(dashboards-mfe): remove redundant config

---

package-lock.json
package.json
projects/dashboards-demo/src/styles.scss
src/styles.scss

build(theme): update optional @simpl/brand dependency

---

projects/live-preview/components/si-live-preview-renderer/si-live-preview-renderer.component.ts

With this change, examples route are initialized earlier and also removed once the component is destroyed.
---

refactor(live-preview): enhance routing

---

projects/element-ng/datepicker/si-timepicker.component.ts

refactor(datepicker): simplify timepicker time parsing

---

playwright/e2e/element-examples/static.spec.ts
playwright/snapshots/static.spec.ts-snapshots/datatable--bootstrap.yaml
src/app/examples/datatable/bootstrap.html

docs(datatable): fix empty table header ally error in bootstrap example

---

projects/charts-ng/src/components/si-chart-gauge/si-chart-gauge.interface.ts
projects/charts-ng/src/components/si-chart-progress-bar/si-chart-progress-bar.interface.ts
projects/charts-ng/src/components/si-chart-progress/si-chart-progress.interface.ts
projects/charts-ng/src/components/si-chart/si-chart.interfaces.ts
projects/charts-ng/src/components/si-custom-legend/si-custom-legend.interface.ts
projects/dashboards-demo/src/environments/environment.prod.ts
projects/element-ng/about/si-about-data.model.ts
projects/element-ng/common/helpers/rtl.ts
projects/element-ng/datepicker/components/test-helper.spec.ts
projects/element-ng/electron-titlebar/electron.helpers.ts
projects/element-ng/file-uploader/si-file-uploader.model.ts
projects/element-ng/filter-bar/filter.ts
projects/element-ng/formly/utils.ts
projects/element-ng/icon/element-icons.ts
projects/element-ng/ip-input/address-utils.ts
projects/element-ng/language-switcher/iso-language-value.ts
projects/element-ng/link/aria-current.model.ts
projects/element-ng/phone-number/si-phone-number-input.models.ts
projects/element-ng/public-api.ts
projects/element-ng/result-details-list/si-result-details-list.datamodel.ts
projects/element-ng/split/si-split.interfaces.ts
projects/element-ng/theme/si-theme.model.ts
projects/element-translate-ng/localize-types/index.d.ts
projects/live-preview/components/si-live-preview-iframe/devices.ts

Makes sure this is not shown in IDE's or rendered in the docs
---

refactor(docs): make sure copyright headers are not JSDoc comments

---

projects/element-ng/icon/si-icon.module.ts

chore(icon-legacy): add legacy icon to module exports

---

playwright/e2e/element-examples/si-list-details.spec.ts
projects/element-ng/list-details/si-details-pane-header/si-details-pane-header.component.ts
projects/element-ng/list-details/si-details-pane/si-details-pane.component.ts
projects/element-ng/list-details/si-list-details.component.html
projects/element-ng/list-details/si-list-details.component.spec.ts
projects/element-ng/list-details/si-list-details.component.ts
src/app/examples/datatable/data.service.ts
src/app/examples/si-list-details/si-list-details-router.html
src/app/examples/si-list-details/si-list-details-router.ts

feat(list-details): support router integration

---

projects/element-ng/navbar-vertical/si-navbar-vertical-group.component.ts

fix(navbar-vertical): support flexible drop down positioning (backport version 47)

---

src/app/examples/datatable/datatable-row-dragging.html
src/app/examples/datatable/datatable-row-dragging.ts
src/assets/i18n/de.json
src/assets/i18n/el.json
src/assets/i18n/en.json
src/assets/i18n/fr.json

docs(datatable): modify example for translating headers

---

playwright/snapshots/si-modal-service.spec.ts-snapshots/si-modals--si-modal-service--icon-element-examples-chromium-dark-linux.png
playwright/snapshots/si-modal-service.spec.ts-snapshots/si-modals--si-modal-service--icon-element-examples-chromium-light-linux.png
playwright/snapshots/si-modal-service.spec.ts-snapshots/si-modals--si-modal-service-element-examples-chromium-dark-linux.png
playwright/snapshots/si-modal-service.spec.ts-snapshots/si-modals--si-modal-service-element-examples-chromium-light-linux.png
src/app/examples/si-modals/app-table.component.html
src/app/examples/si-modals/app-table.component.ts
src/app/examples/si-modals/si-modal-service.html
src/app/examples/si-modals/si-modal-service.ts

chore(demo): add missing examples

---

.github/workflows/build-and-test.yaml
playwright/snapshots/maps/static.spec.ts-snapshots/si-map--si-map-custom-popover-element-examples-chromium-dark-linux.png
playwright/snapshots/maps/static.spec.ts-snapshots/si-map--si-map-custom-popover-onhover-element-examples-chromium-dark-linux.png
playwright/snapshots/maps/static.spec.ts-snapshots/si-map--si-map-custom-zoom-levels-element-examples-chromium-dark-linux.png
playwright/snapshots/maps/static.spec.ts-snapshots/si-map--si-map-default-style-element-examples-chromium-dark-linux.png
playwright/snapshots/maps/static.spec.ts-snapshots/si-map--si-map-grouping-element-examples-chromium-dark-linux.png
playwright/snapshots/maps/static.spec.ts-snapshots/si-map--si-map-labels-element-examples-chromium-dark-linux.png

ci(build): add missing -- separator

---

projects/element-docs-builder/mkdocs_element_docs_builder/index.mjs

build(docs-builder): make sure it works also on Windows

---

src/app/examples/si-list-details/si-list-details.html

Taking care so we don't have to do https://github.com/siemens/element/pull/592
---

docs(list-details): handle overflow in example

---

docs/components/pages/landing-page.md

Fix landing-page docs example.
---

docs(landing-page): fix landing-page docs exemple

---

projects/charts-ng/README.md
projects/element-translate-ng/README.md
projects/live-preview/README.md
projects/maps-ng/README.md

docs: use correct url path for license.md

---

playwright/snapshots/static.spec.ts-snapshots/shapes--shapes-element-examples-chromium-dark-linux.png
playwright/snapshots/static.spec.ts-snapshots/shapes--shapes-element-examples-chromium-light-linux.png
playwright/snapshots/static.spec.ts-snapshots/shapes--shapes.yaml
projects/element-theme/src/styles/variables/_utilities.scss
src/app/examples/shapes/shapes.html

fix(theme): apply correct style for `rounded-end` utility

---

playwright/snapshots/static.spec.ts-snapshots/si-card--si-card-element-examples-chromium-dark-linux.png
playwright/snapshots/static.spec.ts-snapshots/si-card--si-card-element-examples-chromium-light-linux.png
projects/element-ng/card/si-card.component.html
projects/element-ng/card/si-card.component.scss

fix(card): show ellipsis on heading text overflow

---

.github/workflows/vrt-update.yaml

ci: show vrt-update as skipped by default in PR checks

---

projects/element-ng/list-details/si-details-pane/si-details-pane.component.ts

fix(list-details): load route details state on initial load

---

playwright/snapshots/static.spec.ts-snapshots/si-accordion--si-accordion-base-1-element-examples-chromium-dark-linux.png
playwright/snapshots/static.spec.ts-snapshots/si-accordion--si-accordion-base-1-element-examples-chromium-light-linux.png
src/app/examples/si-accordion/si-accordion-base-1.html

chore(demo): make accordion with base-1 example better

---

docs/components/forms-inputs/file-uploader.md

docs(file-uploader): remove deprecated httpclientmodule import

---

.github/workflows/build-and-test.yaml

ci: add code coverage reporting for unit tests

---

projects/element-ng/file-uploader/si-file-uploader.component.ts

fix(file-uploader): allow concurrent uploads in auto-upload mode

---

projects/schematics/siemens-migration/index.spec.ts
projects/schematics/siemens-migration/index.ts
projects/schematics/siemens-migration/mappings/index.ts
projects/schematics/siemens-migration/mappings/style-mappings.ts
projects/schematics/utils/project-utils.ts

- migrate scss files to the new siemens packages
- migrate global styles to the brand package theming
---

feat(schematics): migrate style imports to siemens

---

README.md

chore(readme): add npm badge

---

projects/schematics/siemens-migration/dependency-migration-rule.ts
projects/schematics/siemens-migration/index.spec.ts
projects/schematics/siemens-migration/index.ts
projects/schematics/siemens-migration/mappings/dependency-mappings.ts
projects/schematics/siemens-migration/mappings/index.ts
projects/schematics/siemens-migration/model.ts
projects/schematics/siemens-migration/scss-migration-rule.ts
projects/schematics/siemens-migration/ts-import-migration-rule.ts
projects/schematics/utils/project-utils.ts
projects/schematics/vite-env.d.ts
projects/schematics/vite.config.mts

feat(schematics): implement dependency migration rule

---

projects/element-ng/avatar/si-avatar.component.html
projects/element-ng/avatar/si-avatar.component.ts

refactor(avatar): use signals internally

---

docs/components/buttons-menus/buttons.md
docs/components/forms-inputs/checkbox.md
docs/components/forms-inputs/forms.md
docs/components/forms-inputs/input.md
docs/components/forms-inputs/radio.md
docs/components/status-notifications/avatar.md
docs/fundamentals/layouts/overview.md
docs/patterns/drag-and-drop.md
docs/patterns/loading.md

docs: fix typos

---

package-lock.json

chore(package-lock): update datatable version

---

projects/maps-ng/src/components/si-map/components/si-map-tooltip/si-map-tooltip.component.ts
projects/maps-ng/src/components/si-map/si-map.component.ts

refactor(maps): drop use of deprecated SiTranslateModule

---

playwright/snapshots/si-list-details.spec.ts-snapshots/si-list-details--si-list-details--small-viewport-first-details.yaml
playwright/snapshots/si-list-details.spec.ts-snapshots/si-list-details--si-list-details--small-viewport-second-details.yaml
projects/element-ng/list-details/si-details-pane-header/si-details-pane-header.component.html

fix(list-details): use correct aria label for back icon

---

projects/element-theme/src/styles/components/_datatable.scss

feat(datatable): separator line between pinned and scrollable columns

---

.docs-composerrc.mts
e2e-local.sh
projects/dashboards-ng/README.md
projects/native-charts-ng/README.md

docs: align Siemens copyright notice

---

playwright/snapshots/static.spec.ts-snapshots/si-dashboard--si-timeline-widget-body.yaml
playwright/snapshots/static.spec.ts-snapshots/si-dashboard--si-timeline-widget-element-examples-chromium-dark-linux.png
playwright/snapshots/static.spec.ts-snapshots/si-dashboard--si-timeline-widget-element-examples-chromium-light-linux.png
playwright/snapshots/static.spec.ts-snapshots/si-dashboard--si-timeline-widget.yaml
projects/element-ng/dashboard/widgets/si-timeline-widget/si-timeline-widget-item.component.html
projects/element-ng/dashboard/widgets/si-timeline-widget/si-timeline-widget.component.html
projects/element-ng/dashboard/widgets/si-timeline-widget/si-timeline-widget.component.ts

fix(dashboard): ignore icons on screen reader

---

src/app/examples/dropdown/dropdown-with-overlay.html

Related to https://github.com/siemens/element/pull/588#discussion_r2401580279
---

docs(dropdown): prevent dropdown items focus ring clipping

---

projects/element-ng/datepicker/si-timepicker.component.spec.ts

This MR introduce a WrapperComponent for test which apply a FormControl. This is necessary to verify form control errors
---

test(datepicker): use wrapper component in si-timepicker tests

---

playwright/snapshots/si-daterange.spec.ts-snapshots/si-datepicker--si-date-range-playground--click-through-months-1-element-examples-chromium-dark-linux.png
playwright/snapshots/si-daterange.spec.ts-snapshots/si-datepicker--si-date-range-playground--click-through-months-1-element-examples-chromium-light-linux.png
playwright/snapshots/si-daterange.spec.ts-snapshots/si-datepicker--si-date-range-playground--click-through-months-2-element-examples-chromium-dark-linux.png
playwright/snapshots/si-daterange.spec.ts-snapshots/si-datepicker--si-date-range-playground--click-through-months-2-element-examples-chromium-light-linux.png
playwright/snapshots/si-daterange.spec.ts-snapshots/si-datepicker--si-date-range-playground--ignore-time-1-element-examples-chromium-dark-linux.png
playwright/snapshots/si-daterange.spec.ts-snapshots/si-datepicker--si-date-range-playground--ignore-time-1-element-examples-chromium-light-linux.png
playwright/snapshots/si-daterange.spec.ts-snapshots/si-datepicker--si-date-range-playground--ignore-time-2-element-examples-chromium-dark-linux.png
playwright/snapshots/si-daterange.spec.ts-snapshots/si-datepicker--si-date-range-playground--ignore-time-2-element-examples-chromium-light-linux.png
playwright/snapshots/si-daterange.spec.ts-snapshots/si-datepicker--si-date-range-playground--preview-range-hover-element-examples-chromium-dark-linux.png
playwright/snapshots/si-daterange.spec.ts-snapshots/si-datepicker--si-date-range-playground--preview-range-hover-element-examples-chromium-light-linux.png
playwright/snapshots/si-daterange.spec.ts-snapshots/si-datepicker--si-date-range-playground--selection-element-examples-chromium-dark-linux.png
playwright/snapshots/si-daterange.spec.ts-snapshots/si-datepicker--si-date-range-playground--selection-element-examples-chromium-light-linux.png
projects/element-ng/datepicker/components/test-helper.spec.ts
projects/element-ng/datepicker/date-time-helper.ts
projects/element-ng/datepicker/si-date-range.component.spec.ts
projects/element-ng/datepicker/si-date-range.component.ts
projects/element-ng/datepicker/si-datepicker.directive.ts

feat(datepicker): support 12 hours clock for date-ranges
