siemens/element

.github/workflows/build.yaml

Publish the documentation on main runs.
See for a working version: https://spike-rabbit.github.io/element/components/
Examples are broken because of absolute link, but they should be working with element.siemens.io.
Code is on the main branch.
---

build: deploy examples to GitHub pages on main runs

---

docs/index.md

This PR corrects the link to the demo playground page within the startpage.
---

docs(index): correct link to demo playground

---

.github/workflows/build-and-test.yaml
.github/workflows/publish-documentation.yaml

Splits up the workflow in two parts:
- one workflow for testing and building (build-and-test.yaml)
- one for publishing the documentation (publish-documentation.yaml)
- (there will be a 3rd one for releasing) (release.yaml)
What we need to achieve is running jobs conditional.
While github allows checking for branch name there is no way to trigger a job manually. But we need this to release.
Workflows can be triggered manually and they can be reused.
We have 3 triggers we care about that should to lead slightly different output:
- PR: just run checks
- Push to main: run checks and deploy pages
- Manual release trigger: run checks and publish npm packages
So the publish-documentation and release workflow are reusing the build-and-test workflow.
A working a example of the main job is visible …

build: split workflows into multiple files

---

.github/workflows/release.yaml
.releaserc.yaml
projects/element-ng/package.json
projects/element-theme/package.json
projects/element-translate-ng/package.json
projects/live-preview/package.json

Enables releasing of `@siemens/element-*` packages using a manual triggered workflow.
Also corrects issues with the pre-existing configuration.
Variables are added to the repo.
A working example can be found here: https://github.com/spike-rabbit/element/
Please note that the variables were adjusted accordingly.
---

build: add release pipeline

---

package-lock.json
package.json
projects/element-ng/package.json
projects/element-theme/package.json
projects/element-translate-ng/package.json
projects/live-preview/package.json

Harmonize the package version to 47.0.0
The breaking change notice is need to make semantic-release a new v47.0.0.
In addition I added a v46.0.0 tag before that commit which we should remove later.
---

build: harmonize package versions to 47.0.0

---

CONTRIBUTING.md

Just extends the legal notice with the link to the CLA.
@fh1ch Makes sense or am I missing anything?
---

docs(CONTRIBUTING.md): add info about signing CLA to legal notice

---

.releaserc.yaml
package-lock.json
package.json
projects/element-translate-cli/bin/update-translatable-keys.js
projects/element-translate-cli/package.json

The key extraction must be separated for internal dependency clearing. As the key extraction is not included in an app bundle, its dependencies must not be cleared.
Moving it into its own package allows apps to install it as a dev dependency and therefore exclude it from clearing.
---

feat(element-translation-ng): move key extraction CLI into a separate package

---

projects/element-ng/application-header/si-header-logo.directive.ts
projects/element-ng/application-header/si-header-siemens-logo.component.ts
projects/element-ng/icon/index.ts
projects/element-ng/icon/si-status-icon.component.ts

Voice over currently not understands CSS content alt text. So we add it manually.
Add pending commits from internal repo
---

fix(application-header): announce logo text in Safari / VoiceOver

---

.github/workflows/build-and-test.yaml
package-lock.json
package.json
src/index.html

The OSS repository has a OSS favicon. When building for official deployment, we load the Siemens favicon from our brand package and replace the default favicon.
---

docs(brand): use Siemens favicon

---

.releaserc.js
tools/semantic-release/config.js
tools/semantic-release/writer-opts.js

This pull request introduces a custom semantic-release configuration based on the default preset, tailored to elements project's specific commit conventions and release logic.
- Custom commit analysis logic in `tools/semantic-release/config.js`
- Defines `commitTypes` used in CHANGELOG and the corresponding section titles.
- Controls which types are included or hidden from the CHANGELOG.
- The sorting of the CHANGELOG sections can be done by rearranging the arrays `commitTypes` and `noteTitleMap`
- Automatic version bump logic - determine whether a release is major, minor, or patch based on the commits.
- **major** is triggered by a commit that includes a note with `BREAKING CHANGE` (configurable through [releaserc.js](https://github.com/siemens/element/blob/9f4cc66e5f76ebe1cf7a9e3ffbda285 …

build(semantic-release): add custom configuration

---

CODE_OF_CONDUCT.md

Addressed a small oversight in the `CODE_OF_CONDUCT.md`, using a copied project name.
---

docs(code-of-conduct): correct project name

---

docs/components/layout-navigation/tabs.md

docs(tabs-next): add si-tabs-next examples in docs

---

projects/element-ng/icon/si-status-icon.component.ts

The use of an aria-label is prohibited on
this element, see https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Reference/Attributes/aria-label#associated_roles .
@panch1739 This is our inline notification example:
This change adds a hidden label for the status, so the announced screen reader text is:
`Information Information: Better description of what happened.` (information is doubled).
Is our example "wrong" and the heading would normally not contain the status?
If not we would need to hide the status for inline-notifications.
---

refactor(status-icon): use visually hidden text instead of aria-label

---

projects/element-ng/resize-observer/si-resize-observer.directive.spec.ts
projects/element-ng/resize-observer/si-resize-observer.directive.ts

feat(resize-observer): add emitInitial input to control initial resize emit

---

playwright/snapshots/tabs-next.spec.ts-snapshots/si-tabs--si-tabs-next--tabs-menu-element-examples-chromium-dark-linux.png
playwright/snapshots/tabs-next.spec.ts-snapshots/si-tabs--si-tabs-next--tabs-menu-element-examples-chromium-light-linux.png
playwright/snapshots/tabs-next.spec.ts-snapshots/si-tabs--si-tabs-next--tabs-mobile-element-examples-chromium-dark-linux.png
playwright/snapshots/tabs-next.spec.ts-snapshots/si-tabs--si-tabs-next--tabs-mobile-element-examples-chromium-light-linux.png
projects/element-ng/tabs-next/si-tabset-next.component.html

this also fixes the flaky e2e.

fix(tabs-next): calculate scroll container width correctly on load

---

projects/element-translate-ng/README.md
projects/native-charts-ng/README.md

The license links in npmjs.com is invalid since it is relative.
Other libs also have an absolute URL (ngx-datatable, ionic).
---

docs(README): use absolute urls for links

---

projects/element-ng/tree-view/si-tree-view.component.ts

Describes the API more accurately.
Currently the behaviour is such that enableContextMenuButton must be set true to show the context menu irrespective of whether we need the button or not (for right-clicks at least).
I would also like this to be renamed to enableContextMenu if this is the intended design because the name points that it is only to enable the button and not the whole context menu.
---

docs(tree-view): provide more clarity on usage of enableContextMenuButton

---

projects/charts-ng/src/public-api.module.ts
projects/live-preview/live-preview-routes.ts
projects/live-preview/public-api.module.ts
projects/native-charts-ng/src/public-api.module.ts
src/app/app.config.ts

We previously exported all main modules as `SimplPackageName`. With the open source migration, this got changed partially.
This change now brings back alignment.
The new pattern is `SiPackageName` plus adding a re-export with the old name to avoid breaking changes.
---

refactor: align module names

---

projects/element-ng/breadcrumb/si-breadcrumb.component.ts
projects/element-ng/column-selection-dialog/si-column-selection-dialog.component.ts
projects/element-ng/filtered-search/si-filtered-search.component.ts
projects/element-ng/filtered-search/values/typeahead/si-filtered-search-typeahead.component.ts
projects/element-ng/formly/fields/button/si-formly-button.component.spec.ts
projects/element-ng/formly/fields/text/si-formly-text-display.component.spec.ts
projects/element-ng/language-switcher/si-language-switcher.component.ts
projects/element-ng/link/si-link.directive.spec.ts
projects/element-ng/link/si-link.directive.ts
projects/element-ng/localization/si-locale.service.ts
projects/element-ng/phone-number/si-phone-number-input.component.ts
projects/element-ng/status-bar/si-status-bar.component.ts
projects/element-translate-ng/translate/index.ts
projects/element-translate-ng/translate/si-localize.spec.ts
projects/element-translate-ng/translate/si-localize.ts
projects/element-translate-ng/translate/si-translate.inject.ts
projects/element-translate-ng/translate/si-translate.module.ts
projects/element-translate-ng/translate/si-translate.pipe.ts
projects/element-translate-ng/translate/si-translate.service.ts

This PR fixes the issues with the new angular application unit test builder.
Both are needed as Angular fails with modules in certain cases.
Yet it also helps to fully go standalone.
A follow-up will drop all other usages of the module.
This PR only contains the necessary changes.
We need to keep the module for compatibility.
Moves the initialization out of the module constructor
as the constructor is not reliably called.
The new version ensures that `$localize` is patched
early enough before any other angular initializations.
In order to achieve 100% standalone, we need to get rid of all modules.
Until now, we used a module to ensure
that a correct service instances is created.
This change adds an alternative `injectSiTranslateService`,
which shall replace the `SiTranslateModule`.
Having …

feat(translate): resolve error with new application unit test builder

---

.github/workflows/build-and-test.yaml

No need for a summary, if tests succeeded.
---

build(github): only run e2e summary on failure

---

playwright/e2e/element-examples/si-typeahead.spec.ts
playwright/snapshots/si-typeahead.spec.ts-snapshots/si-typeahead--si-typeahead-basic-element-examples-chromium-dark-linux.png
playwright/snapshots/si-typeahead.spec.ts-snapshots/si-typeahead--si-typeahead-basic-element-examples-chromium-light-linux.png
playwright/snapshots/si-typeahead.spec.ts-snapshots/si-typeahead--si-typeahead-basic.yaml
playwright/snapshots/si-typeahead.spec.ts-snapshots/si-typeahead--si-typeahead-custom-element-examples-chromium-dark-linux.png
playwright/snapshots/si-typeahead.spec.ts-snapshots/si-typeahead--si-typeahead-custom-element-examples-chromium-light-linux.png
playwright/snapshots/si-typeahead.spec.ts-snapshots/si-typeahead--si-typeahead-custom.yaml
src/app/examples/si-typeahead/si-typeahead-async.html
src/app/examples/si-typeahead/si-typeahead-async.ts
src/app/examples/si-typeahead/si-typeahead-basic.html
src/app/examples/si-typeahead/si-typeahead-basic.ts
src/app/examples/si-typeahead/si-typeahead-custom.html
src/app/examples/si-typeahead/si-typeahead-custom.ts
src/app/examples/si-typeahead/si-typeahead-onfocus-scrollable.html
src/app/examples/si-typeahead/si-typeahead-onfocus-scrollable.ts
src/app/examples/si-typeahead/si-typeahead-tokenized.html
src/app/examples/si-typeahead/si-typeahead-tokenized.ts

This does on purpose NOT add the vrts from the static file, as those are redundant.
---

docs(typeahead): add missing examples

---

projects/charts-ng/src/components/si-chart-cartesian/si-chart-cartesian.component.ts
projects/charts-ng/src/shared/themes/element.ts

The series name in the chart tooltip is empty
This is because the `series.name` can be an empty string, in which case, it should fallback to the `series.seriesName` . this does not work right now because of how the `??` operator works

fix(charts): empty series name in tooltip

---

angular.json
package.json

Moving the port definition into the angular.json
---

build(dashboards-demo): use port 4201 by default

---

projects/element-ng/photo-upload/si-photo-upload.component.scss

This happens when the height and width are different (height is more than the width).
Issue was found in a product.
Sample base64 string for testing (https://gist.github.com/prasepic/d53bc69d6937767ac8e35ba751e6331a)
---

fix(photo-upload): remove padding from the sides for default preview

---

package-lock.json
package.json
postversion.js
projects/element-ng/package.json
projects/element-theme/package.json
projects/element-translate-ng/package.json

This should ideally solve our release problem.
The Problem is, that when bumping a package inside the workspace, the dependent packages are not automatically updated.
So they have an invalid peer dependency, since they depend on the old version.
This is hopefully solved by updating all dependent packages directly after a package was bumped.
We previously updated all packages after all were bumped.
This occurs since adding dashboards-ng.
We previously did not have this problem, as I forgot adding `element-ng` to the workspaces.
---

build(release): update version in dependent package right after setting the version

---

CONTRIBUTING.md

Same as https://github.com/siemens/lint/pull/32.
---

docs(contributing): use `release` instead of `maintenance`

---

projects/element-ng/tabs-next/si-tab-next-link.component.ts
projects/element-ng/tabs-next/si-tab-next.component.ts
projects/element-ng/tabs-next/si-tabset-next.component.ts

Previously, in theory the order of tabs could have been wrong. This should never be an issue though, as mixing routing and the buttons tabs should e avoided.
Anyway, this is fixed with this.
---

refactor(tabs-next): use the base class where possible

---

projects/element-ng/tabs-next/si-tabset-next.component.html
projects/element-ng/tabs-next/si-tabset-next.component.ts

This is not needed as the menu itself is only accessible by mouse. So focussing the active option has no impact.
We also should not have this anyway, since internals of the cdk are used.
---

refactor(tabs-next): drop focussing of active tab in the menu

---

projects/element-ng/tabs-next/si-tab-next-base.directive.ts
projects/element-ng/tabs-next/si-tabset-next.component.spec.ts
projects/element-ng/tabs-next/si-tabset-next.component.ts
projects/element-ng/tabs-next/testing/si-tabset-next.harness.ts

Unless actively operated,
the focuskeymanger should initially always point to the active tab. Previously, this only worked if the tabset is initialized with tabs on load. If tabs are added later or the active flag was changed programmatically, tha focuskeymanager was not updated.
This commit ensures
that the focuskeymanager is always updated if the active flag has changed.
---

fix(tabs-next): ensure that the active tab is focussed by default

---

eslint.config.js
projects/element-ng/split/si-split-part.component.ts
projects/element-ng/split/si-split.component.ts
projects/element-ng/tabs/si-tab/si-tab.component.ts
projects/element-ng/tabs/si-tabset/si-tabset.component.ts
projects/live-preview/components/si-live-preview-iframe/si-live-preview-iframe.component.ts
projects/live-preview/components/si-live-preview-qr/si-live-preview-qr.component.ts
projects/live-preview/components/si-live-preview-renderer/si-live-preview-renderer.component.ts
projects/live-preview/components/si-live-preview-renderer/webcomponent/si-live-preview-web.component.ts
projects/live-preview/components/si-live-preview-renderer/webcomponent/si-webcomponent-render.service.ts
src/app/examples/si-filter-settings/si-filter-settings.component.ts

Addresses #234 
This however is a breaking change. `EventEmitter` extends `Subject` by default and is pipeable. 
`output` signal cannot be piped on.
---

refactor(lint): prefer output instead of @Output

---

projects/element-ng/tooltip/si-tooltip.component.html
projects/element-ng/tooltip/si-tooltip.component.ts
projects/element-ng/tooltip/si-tooltip.directive.spec.ts
projects/element-ng/tooltip/si-tooltip.directive.ts
projects/element-ng/tooltip/si-tooltip.service.ts

added `tooltipContext` input which can be used to pass custom template context while using template for `siTooltip`.
This is useful when having tooltip in datatable cells and need to show information based on specific row values.

feat(tooltip): support template context with tooltip template

---

projects/element-ng/tabs-next/si-tab-next-base.directive.ts
projects/element-ng/tabs-next/si-tab-next-link.component.ts
projects/element-ng/tabs-next/si-tab-next.component.ts
projects/element-ng/tabs-next/si-tabset-next.component.ts

Previously, the active flag of all tabs implementation must have been a WritableSignal.
This was causing problems in the link tabs, as there everything is managed by the router.
So we needed an effect to react to changes on the active signal.
Wit this change, we now have methods to programmatically select and deselect tabs.
Those methods never cause the emitting of events and could also be used by applications.
The active flag is now also readonly in the base class to prevent setting it directly
if the router is used.
---

refactor(tabs-next): fully rely on routing for link tabs

---

projects/element-ng/tabs-next/si-tab-next.component.ts
projects/element-ng/tabs-next/si-tabset-next.component.ts
src/app/examples/si-tabs/si-tabs-next-icons.html
src/app/examples/si-tabs/si-tabs-next-icons.ts
src/app/examples/si-tabs/si-tabs-next.html
src/app/examples/si-tabs/si-tabs-next.ts

Using this event in application is pointless.
1. It only works with normal tabs. (but one can also subscribe when using routed tabs)
2. There is a much better option available by listening to the tabs directly.
3. The name is really poor, the main event is an active tab change.
4. It only notifies by user interaction, so one cannot use this to generally track the status.
5. preventing a tab activation violates a11y, is not a typical tab behavior and just in general a very bad approach
Since this is a next component, we can just drop it without a breaking change note.
---

refactor(tabs-next): drop `SiTabsetNextComponent.deselect` event

---

projects/live-preview/components/si-live-preview-wrapper/si-live-preview-wrapper.component.ts

This prevents loops when the client apps fully reloads, e.g. language switching
Fixes #451
---

fix(live-preview): change initialization order to fix locale change loop

---

projects/element-ng/typeahead/si-typeahead.directive.ts

BREAKING CHANGE: Removed `typeaheadOnMultiselectClose` and `typeaheadClosed`. Use `typeaheadOpenChange` instead.

refactor(typeahead): remove deprecations

---

projects/element-ng/tree-view/si-tree-view.component.ts

BREAKING CHANGE: Removed `trackByFunction` which had no effect.

refactor(tree-view): remove deprecations

---

projects/element-ng/tabs-next/si-tab-next.component.ts
projects/element-ng/tabs-next/si-tabset-next.component.ts

The index is no longer needed, so just dropping it.
---

refactor(tabs-next): remove unused `activeTabIndex`

---

projects/element-ng/split/si-split-part.component.ts
projects/element-ng/split/si-split.component.spec.ts

BREAKING CHANGE: Removed unused `headerStatusColor` and `headerStatusIconClass` without any replacement.

refactor(split): remove deprecations

---

karma.shared.cjs
projects/element-ng/auto-collapsable-list/si-auto-collapsable-list.directive.spec.ts

In new headless mode, ResizeObserver takes a long time to fire, delays of 1000ms seem to work, the previous 200ms don't. Firefox is ok. Since this is not testing the behaviour of the service, just mock to updates like in other specs.
---

test(auto-collapsible-list): work around broken ResizeObserver on Chrome headless

---

playwright/snapshots/si-pills-input.spec.ts-snapshots/si-pills-input--si-pills-input-element-examples-chromium-dark-linux.png
playwright/snapshots/si-pills-input.spec.ts-snapshots/si-pills-input--si-pills-input-element-examples-chromium-light-linux.png
projects/element-ng/form/si-form-item/si-form-item.component.html
projects/element-ng/form/si-form.shared.scss

Switch si-form-item from flex wrap to a block-based layout to enhance consistency and maintainability across form elements.
The change enable the use of paddings / margins for checkboxes and radio buttons.
**Prerequisite:** https://github.com/siemens/element/pull/446
---

refactor(form): replace flex wrap with block layout in si-form-item for improved structure

---

playwright/e2e/element-examples/si-select.spec.ts
playwright/snapshots/si-select.spec.ts-snapshots/si-select--si-select--actions-option-created-element-examples-chromium-dark-linux.png
playwright/snapshots/si-select.spec.ts-snapshots/si-select--si-select--actions-option-created-element-examples-chromium-light-linux.png
playwright/snapshots/si-select.spec.ts-snapshots/si-select--si-select--actions-option-created.yaml

Currently, `si-select` e2e test with filters are flaky, these changes will make it stable
---

test(playwright): improve si-select e2e test to remove flakiness

---

projects/element-ng/datepicker/testing/si-datepicker.harness.ts
projects/element-ng/testing/index.ts
tsconfig.json

This ensures that even during development,
only valid paths are accepted.
Previously paths like this worked as well:
`@siemens/element-ng/entrypoint/file-in-entrypoint.ts`.
Since we have the convention that every entry-point has an `index.ts` we can enforce using it.
---

refactor(typescript): use stricter path mappings

---

playwright/snapshots/si-launchpad.spec.ts-snapshots/si-application-header--si-launchpad--mobile.yaml
playwright/snapshots/si-launchpad.spec.ts-snapshots/si-application-header--si-launchpad--new-favorite.yaml
playwright/snapshots/si-launchpad.spec.ts-snapshots/si-application-header--si-launchpad.yaml
projects/element-ng/application-header/launchpad/si-launchpad-factory.component.html
projects/element-ng/application-header/launchpad/si-launchpad-factory.component.ts
projects/element-ng/application-header/launchpad/si-launchpad.model.ts
src/app/examples/si-application-header/si-launchpad.ts

Provides ability to use `routerLink` for apps in launchpad.
Closes #490.
---

feat(launchpad): support `routerLink` for launchpad apps

---

tools/semantic-release/writer-opts.js

Commits with hidden types with notes were not showing their scope, because .map() does not modify the original array and the return value was ignored.
> The term **notes** in the context of semantic release means all options like `NOTE:`, `DEPRECATED:` or `BREAKING CHANGE:`. See the example of the missing scopes in the [v48.0.0-next.1 release changelog](https://github.com/siemens/element/releases/tag/v48.0.0-next.1)
To test this locally the **Testing** section of the original [semantic release pr](https://github.com/siemens/element/pull/28#issue-3083160081) will explain everything.
---

build(semantic-release): fix scope for hidden commit types with notes

---

playwright/snapshots/si-tree-view.spec.ts-snapshots/si-tree-view--si-tree-view-playground--base-tree-element-examples-chromium-dark-linux.png
playwright/snapshots/si-tree-view.spec.ts-snapshots/si-tree-view--si-tree-view-playground--base-tree-element-examples-chromium-light-linux.png
playwright/snapshots/si-tree-view.spec.ts-snapshots/si-tree-view--si-tree-view-playground--base-tree-with-checkbox-element-examples-chromium-dark-linux.png
playwright/snapshots/si-tree-view.spec.ts-snapshots/si-tree-view--si-tree-view-playground--base-tree-with-checkbox-element-examples-chromium-light-linux.png
playwright/snapshots/si-tree-view.spec.ts-snapshots/si-tree-view--si-tree-view-playground--base-tree-with-checkbox.yaml
playwright/snapshots/si-tree-view.spec.ts-snapshots/si-tree-view--si-tree-view-playground--base-tree-with-data-field-2-element-examples-chromium-dark-linux.png
playwright/snapshots/si-tree-view.spec.ts-snapshots/si-tree-view--si-tree-view-playground--base-tree-with-data-field-2-element-examples-chromium-light-linux.png
playwright/snapshots/si-tree-view.spec.ts-snapshots/si-tree-view--si-tree-view-playground--base-tree-with-data-field-2.yaml
playwright/snapshots/si-tree-view.spec.ts-snapshots/si-tree-view--si-tree-view-playground--base-tree.yaml
playwright/snapshots/si-tree-view.spec.ts-snapshots/si-tree-view--si-tree-view-playground--expand-collapse-element-examples-chromium-dark-linux.png
playwright/snapshots/si-tree-view.spec.ts-snapshots/si-tree-view--si-tree-view-playground--expand-collapse-element-examples-chromium-light-linux.png
playwright/snapshots/si-tree-view.spec.ts-snapshots/si-tree-view--si-tree-view-playground--expand-collapse.yaml
playwright/snapshots/si-tree-view.spec.ts-snapshots/si-tree-view--si-tree-view-playground--flat-tree-element-examples-chromium-dark-linux.png
playwright/snapshots/si-tree-view.spec.ts-snapshots/si-tree-view--si-tree-view-playground--flat-tree-element-examples-chromium-light-linux.png
playwright/snapshots/si-tree-view.spec.ts-snapshots/si-tree-view--si-tree-view-playground--flat-tree.yaml
playwright/snapshots/si-tree-view.spec.ts-snapshots/si-tree-view--si-tree-view-playground--grouped-tree-element-examples-chromium-dark-linux.png
playwright/snapshots/si-tree-view.spec.ts-snapshots/si-tree-view--si-tree-view-playground--grouped-tree-element-examples-chromium-light-linux.png
playwright/snapshots/si-tree-view.spec.ts-snapshots/si-tree-view--si-tree-view-playground--grouped-tree.yaml
playwright/snapshots/static.spec.ts-snapshots/si-tree-view--si-tree-view.yaml
projects/element-ng/tree-view/si-tree-view-item/si-tree-view-item.component.html
projects/element-ng/tree-view/si-tree-view-item/si-tree-view-item.component.ts
projects/element-ng/tree-view/si-tree-view.component.spec.ts
projects/element-ng/tree-view/si-tree-view.component.ts
src/app/examples/si-tree-view/si-tree-view-playground.html
src/app/examples/si-tree-view/si-tree-view-playground.ts

BREAKING CHANGE: Removed `SiTreeViewComponent.disableFilledIcons` input.
Tree items no longer show a filled icon on selection.
---

feat(tree-view): remove `SiTreeViewComponent.disableFilledIcons` input

---

projects/element-ng/list-details/si-details-pane-header/si-details-pane-header.component.scss

Need a new stacking context so the focus outline of the back button also shows when not hovering
---

fix(list-details): make back button outline complete on focus

---

projects/element-theme/src/styles/bootstrap/forms/_form-label.scss

This is a preparation for the help pattern where we need the line-height of 16px (default).
---

refactor(form): use same spacing/line-height as in figma

---

projects/element-ng/navbar-vertical/si-navbar-vertical-group.component.ts

The vertical navigation menu didn't support flexible positioning since the `cdk-overlay-pane` size was always 0.
Since the `cdk-overlay-pane` size was always zero, the content of the vertical navbar dropdown was always forced to fit, causing it to incorrectly render in the initial position of the `SiNavbarVerticalGroupTriggerDirective`.
---

fix(navbar-vertical): support flexible drop down positioning

---

angular.json

Currently, when we try to build mfe project in dashboards-demo build fails due to missing webpack config file. This change will add that file.
---

build(dashboards-demo): remove extraWebpackConfig from build configurations

---

playwright/snapshots/static.spec.ts-snapshots/typography--type-styles-element-examples-chromium-dark-linux.png
playwright/snapshots/static.spec.ts-snapshots/typography--type-styles-element-examples-chromium-light-linux.png
playwright/snapshots/static.spec.ts-snapshots/typography--type-styles.yaml
src/app/examples/typography/type-styles.html

Updates the typography semantic for the leftover type-styles example.
---

refactor(examples): adapt type-styles to latest typography definition

---

.github/workflows/build-and-test.yaml
projects/maps-ng/src/components/si-map/si-map.component.spec.ts

when tests runs they cannot find our tokens and falls back to empty string which openlayer doesn't like and breaks.

test(maps): use dummy fallbacks for color tokens

---

projects/element-ng/formly/fields/date-range/si-formly-date-range.component.html
projects/element-ng/formly/fields/date-range/si-formly-date-range.component.ts
projects/element-ng/formly/fields/datetime/si-formly-datetime.component.html
projects/element-ng/formly/fields/datetime/si-formly-datetime.component.ts
projects/element-ng/formly/fields/email/si-formly-email.component.html
projects/element-ng/formly/fields/email/si-formly-email.component.ts
projects/element-ng/formly/fields/ip-input/si-formly-ip-input.component.html
projects/element-ng/formly/fields/ip-input/si-formly-ip-input.component.ts
projects/element-ng/formly/fields/number/si-formly-number.component.html
projects/element-ng/formly/fields/number/si-formly-number.component.ts
projects/element-ng/formly/fields/password/si-formly-password.component.html
projects/element-ng/formly/fields/password/si-formly-password.component.ts
projects/element-ng/formly/fields/select/si-formly-select.component.html
projects/element-ng/formly/fields/select/si-formly-select.component.ts
projects/element-ng/formly/fields/textarea/si-formly-textarea.component.html
projects/element-ng/formly/fields/textarea/si-formly-textarea.component.ts
projects/element-ng/formly/fields/time/si-formly-time.component.ts
projects/element-ng/formly/utils.ts
projects/element-ng/formly/wrapper/si-formly-wrapper.component.html
projects/element-ng/formly/wrapper/si-formly-wrapper.component.ts

The automatic linking by the `si-form-item` does not work due to broken dependency injection.
So we must link it ourselves.
In the long run, we should stop using the `si-form-item` in `si-formly`.
---

fix(formly): link error messages to custom controls

---

projects/element-ng/icon-status/ng-package.json
projects/element-ng/icon-status/si-icon-status.component.ts
projects/element-ng/icon-status/si-icon-status.module.ts

The PR https://github.com/siemens/element/pull/632 was missing the ng-package.json file for the deprecated module.
---

fix(icon-status): add missing ng-package.json file

---

projects/element-ng/icon/si-icon.component.ts
projects/element-ng/icon/si-icons.ts

Reported from a project...
For ex - In side panel content, click on content1 [exapmple](https://element.siemens.io/element-examples/#/viewer/editor?theme=dark&locale=en&t=%0A%3Csi-side-panel%20%23sidePanel%20%5Bcollapsed%5D%3D%22true%22%20%5Bmode%5D%3D%22mode%22%20%5Bsize%5D%3D%22size%22%3E%0A%20%20%3Cdiv%20class%3D%22has-navbar-fixed-top%20px-6%22%3E%0A%20%20%20%20%3Csi-application-header%3E%0A%20%20%20%20%20%20%3Csi-header-brand%3E%0A%20%20%20%20%20%20%20%20%3Ca%20siHeaderLogo%20routerLink%3D%22%2F%22%20class%3D%22d-none%20d-md-flex%22%3E%3C%2Fa%3E%0A%20%20%20%20%20%20%20%20%3Ch1%20class%3D%22application-name%22%3ESide%20panel%20portal%3C%2Fh1%3E%0A%20%20%20%20%20%20%3C%2Fsi-header-brand%3E%0A%20%20%20%20%3C%2Fsi-application-header%3E%0A%20%20%20%20%3Cbr%20%2F%3E%0A%20%20%20%20%3Cbutton% …

fix(icon): handle undefined icon use case

---

projects/element-ng/datatable/si-datatable-interaction.directive.ts

allow `siDatatableInteraction` to be applied only on `ngx-datatable` and use direct `DatatableComponent` instance values for `selectionType` and `virtualization`.
---

refactor(datatable): use `siDatatableInteraction` only with ngx-datatable

---

docs/patterns/help.md
mkdocs.yml

This PR adds a link in the help patterns to the help button, and corrects the order of the chapters in the button and menu section.
---

docs(help-patterns): add link to help button

---

.releaserc.js

This PR addresses 4 points:
- v48 releases are marked as pre-release in GitHub and miss the `latest` tag on npmjs.com
- v47.x maintenance releases should have the `range` property set to ensure no accidential releaes of a major version happens form a maintenance branch
- we're currently releasing our RCs as `.next-X` versions, which is OK, but RC is more specific and so we should use RC also here.
- the release pipeline for v48.0.1 failed because it tried to publish `dashboards-demo`, so removing that here.
AI summary for the first 3 fixes about the branches config:
The issue you're describing—where a release from the `main` branch unexpectedly gets treated as a prerelease—is most likely caused by the order of branches in your configuration array. Semantic-release processes the branches …

chore(releaserc.js): use proper branches config for semantic release

---

.releaserc.js

chore/use proper branches config for semantic release backport in releaserc.js

---

projects/element-ng/datepicker/si-timepicker.component.spec.ts
projects/element-ng/datepicker/si-timepicker.component.ts

- Only update meridian to PM when the  user enter a hour value greater 12
---

fix(datepicker): update the AM/PM meridian for 12-hour clock

---

projects/element-ng/dashboard/si-dashboard-card.component.ts
projects/element-ng/dashboard/si-dashboard.component.ts
projects/element-ng/dashboard/widgets/si-link-widget.component.ts
projects/element-ng/dashboard/widgets/si-list-widget/si-list-widget-body.component.ts
projects/element-ng/dashboard/widgets/si-list-widget/si-list-widget-item.component.ts
projects/element-ng/dashboard/widgets/si-list-widget/si-list-widget.component.ts
projects/element-ng/dashboard/widgets/si-timeline-widget/si-timeline-widget-item.component.ts
projects/element-ng/dashboard/widgets/si-timeline-widget/si-timeline-widget.component.ts
projects/element-ng/dashboard/widgets/si-value-widget-body.component.ts
projects/element-ng/dashboard/widgets/si-value-widget.component.ts

dropped import of `SiTranslateModule` with `SiTranslatePipe`

refactor(dashboard): drop use of deprecated module

---

projects/element-ng/datepicker/si-timepicker.component.html
projects/element-ng/datepicker/si-timepicker.component.ts

The validation of the input field limits was not correct:
- On user input hours 24 the field is invalid
- On user input minutes 60 the field is invalid
- On user input seconds 60 the field is invalid
- if one of the input field contain an invalid value we should not expose an previous value instead the value is set to undefined
---

fix(datepicker): correct si-timepicker input field validation

---

playwright/snapshots/si-tree-view.spec.ts-snapshots/si-tree-view--si-tree-view-playground--expand-collapse.yaml
projects/element-ng/tree-view/si-tree-view.component.html

fix(tree-view): use aria label for expand collapse icons

---

projects/element-ng/filtered-search/si-filtered-search.component.spec.ts
projects/element-ng/filtered-search/values/typeahead/si-filtered-search-typeahead.component.ts

Previously, the text was not cleared visually but in the internal data. This change also removes the text visually.
---

fix(filtered-search): visually clear input text in active mode if clear is pressed
